[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = """ qemu-system-riscv64
  -serial mon:stdio
  -cpu rv64
  -machine virt
  -m 150M
  -s
  -nographic
  -bios """